function breakscreen2()
% BREAKSCREEN2 The title and explanation input for the function
% generate_form.
% This function makes it possible to write a title and explanation on the
% GUI screen. The input should be written in this function itself and both
% should be a string.
title = "The visual search task!";
explanation = "In this task you" + ...
 " will be required to find a target in a field of distractors. The " + ...
 "target will be different from all other symbols shown on screen. " + ...
 "Targets will be shown in a different colour or a different shape " + ...
 "from the rest.                                                                                               " + ...
 "If a target is present press “j” and a new screen will " + ...
 "be shown. If the target is absent press “f”. Try to answer as quickly " + ...
 "as possible and do not feel too bad if you make a mistake. First we " + ...
 "will start with some practice rounds. Afterwards the real experiment " + ...
 "will start.                                                                                            " + ...
 "Good luck!";

generate_form(title, explanation, [], []);
end
